DROP TABLE IF EXISTS PLANTS;

CREATE TABLE PLANTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  lastWateredDate VARCHAR(250) NOT NULL,
  wateringFreq VARCHAR(250) NOT NULL
);